export const GET_ALERT = 'GET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE';

export const GET_DASHBOARD_DIONAEA_COUNT_SUCCESS = 'GET_DASHBOARD_DIONAEA_COUNT_SUCCESS';
export const GET_DASHBOARD_DIONAEA_COUNT_FAILURE = 'GET_DASHBOARD_DIONAEA_COUNT_FAILURE';

export const GET_DASHBOARD_WEB_COUNT_SUCCESS = 'GET_DASHBOARD_WEB_COUNT_SUCCESS';
export const GET_DASHBOARD_WEB_COUNT_FAILURE = 'GET_DASHBOARD_WEB_COUNT_FAILURE';

export const GET_DASHBOARD_IPTABLE_COUNT_SUCCESS = 'GET_DASHBOARD_IPTABLE_COUNT_SUCCESS';
export const GET_DASHBOARD_IPTABLE_COUNT_FAILURE = 'GET_DASHBOARD_IPTABLE_COUNT_FAILURE';

export const GET_DASHBOARD_TOKEN_SUMMARY_SUCCESS = 'GET_DASHBOARD_TOKEN_SUMMARY_SUCCESS';
export const GET_DASHBOARD_TOKEN_SUMMARY_FAILURE = 'GET_DASHBOARD_TOKEN_SUMMARY_FAILURE';
export const GET_NEW_BEACON_URL_SUCCESS = 'GET_NEW_BEACON_URL_SUCCESS';
export const GET_IP_NMAP_DETAILS = 'GET_IP_NMAP_DETAILS';
export const GET_INTEL_DETAILS = 'GET_INTEL_DETAILS';
export const START_NMAP_SCAN = 'START_NMAP_SCAN';
export const START_INTEL_GATHERING = 'START_INTEL_GATHERING';
export const STOP_INTEL_GATHERING = 'STOP_INTEL_GATHERING';
export const STOP_NMAP_SCAN = 'STOP_NMAP_SCAN';
export const CLEAR_MEMORY = 'CLEAR_MEMORY';
export const GET_DASHBOARD_COMPROMISED_BEACONS_SUCCESS =
  'GET_DASHBOARD_COMPROMISED_BEACONS_SUCCESS';
export const GET_DASHBOARD_COMPROMISED_BEACONS_FAILURE =
  'GET_DASHBOARD_COMPROMISED_BEACONS_FAILURE';

export const GET_DASHBOARD_COUNTRY_INTERACTIONS_SUCCESS =
  'GET_DASHBOARD_COUNTRY_INTERACTIONS_SUCCESS';
export const GET_DASHBOARD_COUNTRY_INTERACTIONS_FAILURE =
  'GET_DASHBOARD_COUNTRY_INTERACTIONS_FAILURE';

export const GET_DASHBOARD_HONEYPOT_MACHINE_DATA_SUCCESS =
  'GET_DASHBOARD_HONEYPOT_MACHINE_DATA_SUCCESS';
export const GET_DASHBOARD_HONEYPOT_MACHINE_DATA_FAILURE =
  'GET_DASHBOARD_HONEYPOT_MACHINE_DATA_FAILURE';

export const GET_BEACONS_DATA_SUCCESS = 'GET_BEACONS_DATA_SUCCESS';
export const GET_BEACONS_DATA_FAILURE = 'GET_BEACONS_DATA_FAILURE';

export const GET_BEACON_SUMMARY_DATA_SUCCESS = 'GET_BEACON_SUMMARY_DATA_SUCCESS';
export const GET_BEACON_SUMMARY_DATA_FAILURE = 'GET_BEACON_SUMMARY_DATA_FAILURE';

export const GET_NEW_BEACON_FILE_SUCCESS = 'GET_NEW_BEACON_FILE_SUCCESS';
export const GET_NEW_BEACON_FILE_FAILURE = 'GET_NEW_BEACON_FILE_FAILURE';

export const GET_ATTACKER_LOCATION_SUCCESS = 'GET_ATTACKER_LOCATION_SUCCESS';
export const GET_ATTACKER_LOCATION_FAILURE = 'GET_ATTACKER_LOCATION_FAILURE';

export const GET_SMB_DATA_SUCCESS = 'GET_SMB_DATA_SUCCESS';
export const GET_SMB_DATA_FAILURE = 'GET_SMB_DATA_FAILURE';

export const GET_SMB_TIMESTAMPS_SUCCESS = 'GET_SMB_TIMESTAMPS_SUCCESS';
export const GET_SMB_TIMESTAMPS_FAILURE = 'GET_SMB_TIMESTAMPS_FAILURE';

export const GET_SMB_REPORTS_SUCCESS = 'GET_SMB_REPORTS_SUCCESS';
export const GET_SMB_REPORTS_FAILURE = 'GET_SMB_REPORTS_FAILURE';

export const GET_ALL_IPS_SUCCESS = 'GET_ALL_IPS_SUCCESS';
export const GET_ALL_IPS_FAILURE = 'GET_ALL_IPS_FAILURE';

export const GET_IP_PROFILING_SUCCESS = 'GET_IP_PROFILING_SUCCESS';
export const GET_IP_PROFILING_FAILURE = 'GET_IP_PROFILING_FAILURE';

export const GET_IP_TABLE_INTERACTIONS_SUCCESS = 'GET_IP_TABLE_INTERACTIONS_SUCCESS';
export const GET_IP_TABLE_INTERACTIONS_FAILURE = 'GET_IP_TABLE_INTERACTIONS_FAILURE';

export const GET_IP_TABLE_SCANS_SUCCESS = 'GET_IP_TABLE_SCANS_SUCCESS';
export const GET_IP_TABLE_SCANS_FAILURE = 'GET_IP_TABLE_SCANS_FAILURE';

export const GET_WEB_DATA_SUCCESS = 'GET_WEB_DATA_SUCCESS';
export const GET_WEB_DATA_FAILURE = 'GET_WEB_DATA_FAILURE';

export const GET_WEB_TIMESTAMP_SUCCESS = 'GET_WEB_TIMESTAMP_SUCCESS';
export const GET_WEB_TIMESTAMP_FAILURE = 'GET_WEB_TIMESTAMP_FAILURE';

export const GET_ATTACKER_TOKENS = 'GET_ATTACKER_TOKENS';

export const GET_MITRE_NAVIGATOR_SUCCESS = 'GET_MITRE_NAVIGATOR_SUCCESS';
export const GET_MITRE_NAVIGATOR_FAILURE = 'GET_MITRE_NAVIGATOR_FAILURE';

export const GET_ATTACK_PATHS_SUCCESS = 'GET_ATTACK_PATHS_SUCCESS';
export const GET_ATTACK_PATHS_FAILURE = 'GET_ATTACK_PATHS_FAILURE';

export const GET_FILTERED_ATTACK_PATHS_SUCCESS = 'GET_FILTERED_ATTACK_PATHS_SUCCESS';
